- name: install mariadb
  apt:
    pkg:
    - mariadb-server
    - python-mysqldb

- name: Create a new database with name 'wordpress_db'
  mysql_db:
    name: wordpress_db
    state: present

- name: Create database user with name 'wordpress' and password 'wordpress'
  with_items:
  - bind-address=0.0.0.0
  mysql_user:
    name: wordpress
    password: wordpress
    priv: 'wordpress_db.*:ALL'
    state: present
