- name: install mariadb
  apt:
    pkg:
    - mariadb-server
    - python-mysqldb

- name: Create a new database with name 'wordpress_db'
  mysql_db:
    name: wordpress_db
    state: present

- name: Create database user with name 'wordpress' and password 'wordpress'
  mysql_user:
    name=wordpress
    password=wordpress
    priv='wordpress_db.*:ALL'
    host=%
    state=present

- name: Copy conf bind address
  copy: > 
    src=50-server.cnf
    dest=/etc/mysql/mariadb.conf.d/50-server.cnf
  notify:
  - restart mariadb

